"""empty message

Revision ID: 3ab0a8e5dd5e
Revises: a925d47e3b84
Create Date: 2021-07-18 11:38:57.122586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab0a8e5dd5e'
down_revision = 'a925d47e3b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FlaggedEmail', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.drop_column('FlaggedEmail', 'dateIssued')
    op.add_column('FlaggedImage', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.drop_column('FlaggedImage', 'dateIssued')
    op.add_column('IssuedTicket', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.drop_column('IssuedTicket', 'dateIssued')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IssuedTicket', sa.Column('dateIssued', sa.DATE(), nullable=False))
    op.drop_column('IssuedTicket', 'datetime')
    op.add_column('FlaggedImage', sa.Column('dateIssued', sa.DATE(), nullable=False))
    op.drop_column('FlaggedImage', 'datetime')
    op.add_column('FlaggedEmail', sa.Column('dateIssued', sa.DATE(), nullable=False))
    op.drop_column('FlaggedEmail', 'datetime')
    # ### end Alembic commands ###
