"""empty message

Revision ID: 50c6cc696554
Revises: 3ab0a8e5dd5e
Create Date: 2021-07-21 16:33:55.178960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50c6cc696554'
down_revision = '3ab0a8e5dd5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=64), nullable=False),
    sa.Column('isAdmin', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_index('username', table_name='Officer')
    op.drop_table('Officer')
    op.drop_index('username', table_name='Admin')
    op.drop_table('Admin')
    op.create_unique_constraint(None, 'FlaggedEmail', ['incidentID'])
    op.create_unique_constraint(None, 'FlaggedImage', ['incidentID'])
    op.create_unique_constraint(None, 'IssuedTicket', ['incidentID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'IssuedTicket', type_='unique')
    op.drop_constraint(None, 'FlaggedImage', type_='unique')
    op.drop_constraint(None, 'FlaggedEmail', type_='unique')
    op.create_table('Admin',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'Admin', ['username'], unique=True)
    op.create_table('Officer',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'Officer', ['username'], unique=True)
    op.drop_table('User')
    # ### end Alembic commands ###
