"""empty message

Revision ID: 678b27d65177
Revises: 14464242165b
Create Date: 2021-07-17 16:59:18.321398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '678b27d65177'
down_revision = '14464242165b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FlaggedEmail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trn', sa.String(length=10), nullable=False),
    sa.Column('incidentID', sa.Integer(), nullable=False),
    sa.Column('dateIssued', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['incidentID'], ['Incident.id'], ),
    sa.ForeignKeyConstraint(['trn'], ['VehicleOwner.trn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FlaggedImage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incidentID', sa.Integer(), nullable=False),
    sa.Column('dateIssued', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['incidentID'], ['Incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IssuedTicket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trn', sa.String(length=10), nullable=False),
    sa.Column('incidentID', sa.Integer(), nullable=False),
    sa.Column('dateIssued', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['incidentID'], ['Incident.id'], ),
    sa.ForeignKeyConstraint(['trn'], ['VehicleOwner.trn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Ticket')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ticket',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('trn', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('incidentID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('dateIssued', sa.DATE(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['incidentID'], ['Incident.id'], name='Ticket_ibfk_1'),
    sa.ForeignKeyConstraint(['trn'], ['VehicleOwner.trn'], name='Ticket_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('IssuedTicket')
    op.drop_table('FlaggedImage')
    op.drop_table('FlaggedEmail')
    # ### end Alembic commands ###
