"""empty message

Revision ID: fa6f695c9302
Revises: 50c6cc696554
Create Date: 2021-07-24 15:43:17.313839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa6f695c9302'
down_revision = '50c6cc696554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('IssuedTicket', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=70),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('IssuedTicket', 'status',
               existing_type=sa.String(length=70),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
